### ISSUE TITLE
Linux: Screen Ghosting & Dot Matrix intensity revert to 0

### ISSUE THREAD

**Issue by GyoMan** [drhelius/Gearboy#191]
Gearboy-3.7.0-3-g59352a8-ubuntu-24.04:

Linux Mint 22.1: No matter what values i set for Screen Ghosting & Dot Matrix intensity, they always revert to 0 when i reopen Gearboy. All other values (like Bilinear filtering) are saved and read ok.

I also tried a few more versions from Actions and all have the same problem.

**Comment by drhelius** [comment]
I checked and I can't see any issue. It is probably a problem reading or writing the settings file.

If you run the emu from the command line there is a log tracing indicating where is trying to load the settings file. Something like "Loading settings from...".

Try deleting the file, the emulator will create a new one with default values. Check the permissions of the folder too.

In addition, if you can compile it form sources you can use `make DEBUG=1`. Then it will output a lot of debugging info when writing and loading the settings file that can give us some clues.

**Comment by GyoMan** [comment]
It is a Region problem. When the config.ini is saved all decimal values are saved separated by (,)  for example: **MixFramesIntensity = 0,600000**

This value can't be read back. If i manually set **MixFramesIntensity = 0.600000** it works fine (until it overwrites the config.ini again and places , in place of . )

**Comment by drhelius** [comment]
oh! thanks for the update, can you share your "locale"?
I'll check if I can try to ignore it.

**Comment by GyoMan** [comment]
el_GR

**Comment by drhelius** [comment]
Check this build, it should fix it:

https://github.com/drhelius/Gearboy/actions/runs/14602928816

**Comment by GyoMan** [comment]
Not fixed... The values are still saved with , in decimal points:

MixFramesIntensity = 0,75

**Comment by drhelius** [comment]
Let me check again

**Comment by drhelius** [comment]
Hopefully this will finally fix it:
https://github.com/drhelius/Gearboy/actions/runs/14612699201

**Comment by GyoMan** [comment]
Fixed! Thanks!
